### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by sushen** [manishankarvakta/crypto#1]
![Best-Bitcoin-mining-software-available](https://user-images.githubusercontent.com/4492335/105666974-ab194500-5f04-11eb-9028-282d283e9ef3.jpg)

![trade cryptocurrencies](https://user-images.githubusercontent.com/4492335/105667008-c1270580-5f04-11eb-8e28-6ec4d5cd205f.jpeg)

**Comment by manishankarvakta** [comment]
add screen .
